version: "3.9"

services:
  aspencapital-war-db:
    container_name: aspencapital-war-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - aspencapital-war-sqldata:/var/opt/sqldata
  aspencapital-war-api:
    container_name: aspencapital-war-api
    build:
      context: .
      dockerfile: AspenCapital.Api.War/Dockerfile
    depends_on:
      - aspencapital-war-db

volumes:
  aspencapital-war-sqldata:
    external: false