// <auto-generated />
using System;
using AspenCapital.Data.War;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspenCapital.Data.War.Migrations
{
    [DbContext(typeof(WarContext))]
    [Migration("20211114221852_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspenCapital.Data.War.Entities.CardValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CardValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Two",
                            Symbol = "2",
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Three",
                            Symbol = "3",
                            Weight = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Four",
                            Symbol = "4",
                            Weight = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Five",
                            Symbol = "5",
                            Weight = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Six",
                            Symbol = "6",
                            Weight = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Seven",
                            Symbol = "7",
                            Weight = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Eight",
                            Symbol = "8",
                            Weight = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "Nine",
                            Symbol = "9",
                            Weight = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ten",
                            Symbol = "10",
                            Weight = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jack",
                            Symbol = "J",
                            Weight = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "Queen",
                            Symbol = "Q",
                            Weight = 11
                        },
                        new
                        {
                            Id = 12,
                            Name = "King",
                            Symbol = "K",
                            Weight = 12
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ace",
                            Symbol = "A",
                            Weight = 13
                        });
                });

            modelBuilder.Entity("AspenCapital.Data.War.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Player2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalMovements")
                        .HasColumnType("int");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("AspenCapital.Data.War.Entities.GameMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsWar")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Player1Cards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player1DeckCount")
                        .HasColumnType("int");

                    b.Property<int>("Player1WonCardsCount")
                        .HasColumnType("int");

                    b.Property<string>("Player2Cards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player2DeckCount")
                        .HasColumnType("int");

                    b.Property<int>("Player2WonCardsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameMovements");
                });

            modelBuilder.Entity("AspenCapital.Data.War.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04c0b9df-a162-4fc8-fb52-08d9a3beeb17"),
                            Name = "Player A"
                        },
                        new
                        {
                            Id = new Guid("04c0b9df-a162-4fc8-fb52-08d9a3beeb18"),
                            Name = "Player B"
                        });
                });

            modelBuilder.Entity("AspenCapital.Data.War.Entities.Suit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            Name = "Clubs"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Red",
                            Name = "Diamonds"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Red",
                            Name = "Hearts"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Black",
                            Name = "Spades"
                        });
                });

            modelBuilder.Entity("AspenCapital.Data.War.Entities.Game", b =>
                {
                    b.HasOne("AspenCapital.Data.War.Entities.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspenCapital.Data.War.Entities.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspenCapital.Data.War.Entities.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("AspenCapital.Data.War.Entities.GameMovement", b =>
                {
                    b.HasOne("AspenCapital.Data.War.Entities.Game", "Game")
                        .WithMany("Movements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AspenCapital.Data.War.Entities.Game", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
